refactor: Url swap from gitlab.axr->source.goxbe.io

diff --git a/docker/Dockerfile.build b/docker/Dockerfile.build
--- a/docker/Dockerfile.build
+++ b/docker/Dockerfile.build
@@ -10,9 +10,9 @@ CMD echo '--------------' && \
       echo '[GITLAB_ACCESS_TOKEN] Not set. Skipping access token injection.'; \
     else \
       echo '[GITLAB_ACCESS_TOKEN] Injecting GitLab access token into the repository URL...' && \
-      git config --global url."https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.acceleratxr.com/".insteadOf "https://gitlab.acceleratxr.com/" && \
+      git config --global url."https://oauth2:$GITLAB_ACCESS_TOKEN@source.goxbe.io/".insteadOf "https://source.goxbe.io/" && \
       echo 'Verifying the URL swap...' && \
-      git ls-remote https://gitlab.acceleratxr.com/Core/xbe_docs.git || { echo 'GITLAB_ACCESS_TOKEN URL swap verification failed: Bad perms? Expired?'; exit 1; }; \
+      git ls-remote https://source.goxbe.io/Core/xbe_docs.git || { echo 'GITLAB_ACCESS_TOKEN URL swap verification failed: Bad perms? Expired?'; exit 1; }; \
     fi && \
     echo && \
     cd docs && make html
