fix!: Injected GITLAB_ACCESS_TOKEN secret key swap
[XBND-643] Thomas' Docker image project
- See readme

diff --git a/docker/Dockerfile.build b/docker/Dockerfile.build
--- a/docker/Dockerfile.build
+++ b/docker/Dockerfile.build
@@ -2,4 +2,17 @@ FROM docs-base
 
 # NOTE: symlink_to_repo_manager.py appears to cause errors when building docs..
 # CMD cd tools && python ./symlink_to_repo_manager.py && cd ../docs && make html
-CMD cd docs && make html
+CMD echo '--------------' && \
+    echo '[post_create_environment] Running post_create_environment setup...' && \
+    echo 'Working Dir: ' && pwd && \
+    set -e && \
+    if [ -z "$GITLAB_ACCESS_TOKEN" ]; then \
+      echo '[GITLAB_ACCESS_TOKEN] Not set. Skipping access token injection.'; \
+    else \
+      echo '[GITLAB_ACCESS_TOKEN] Injecting GitLab access token into the repository URL...' && \
+      git config --global url."https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.acceleratxr.com/".insteadOf "https://gitlab.acceleratxr.com/" && \
+      echo 'Verifying the URL swap...' && \
+      git ls-remote https://gitlab.acceleratxr.com/Core/acceleratxr.io.git || { echo 'GITLAB_ACCESS_TOKEN URL swap verification failed: Bad perms? Expired?'; exit 1; }; \
+    fi && \
+    echo && \
+    cd docs && make html
