chore!: Rename acceleratxr.io repo to xbe_docs
[XBND-1140] Rename acceleratxr.io repo -> to xbe_docs

diff --git a/docker/Dockerfile.build b/docker/Dockerfile.build
--- a/docker/Dockerfile.build
+++ b/docker/Dockerfile.build
@@ -12,7 +12,7 @@ CMD echo '--------------' && \
       echo '[GITLAB_ACCESS_TOKEN] Injecting GitLab access token into the repository URL...' && \
       git config --global url."https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.acceleratxr.com/".insteadOf "https://gitlab.acceleratxr.com/" && \
       echo 'Verifying the URL swap...' && \
-      git ls-remote https://gitlab.acceleratxr.com/Core/acceleratxr.io.git || { echo 'GITLAB_ACCESS_TOKEN URL swap verification failed: Bad perms? Expired?'; exit 1; }; \
+      git ls-remote https://gitlab.acceleratxr.com/Core/xbe_docs.git || { echo 'GITLAB_ACCESS_TOKEN URL swap verification failed: Bad perms? Expired?'; exit 1; }; \
     fi && \
     echo && \
     cd docs && make html
